### ISSUE TITLE
All deployed VMs must have a public IP to contact the BOSH Director

### ISSUE THREAD

**Issue by ljfranklin** [frodenas/bosh-google-cpi-boshrelease#2]
Because GCE does not allow static assignment of private IP addresses, the BOSH Director endpoints (e.g. registry) can only be configured with the Director's public IP.  Therefore, all of the VMs also need public IP addresses. This effectively means that setting `cloud_properties.ephemeral_external_ip: false` on private networks breaks the Director <--> Agent communication.

It is possible to [set up GCE routes](https://cloud.google.com/compute/docs/instances-and-network#staticnetworkaddress), to direct requests for a given private IP to a particular instance. The setting could be performed by the CPI. e.g., when the VM comes up, determine its private IP and add a matching route.

**Comment by frodenas** [comment]
Thanks @ljfranklin for reporting this. This is a known gap, and a similar suggestion has been made at https://github.com/frodenas/bosh-google-cpi/issues/1 by using a combination of `manual networks` and `GCE routes`.

Setting up GCE routes only makes sense if the CPI supports `manual networks`, otherwise there's no need to configure routes as GCE will automatically configure them when using private subnetworks.

I'm not a big fan of using GCE routes, as it leads to a complex scenario: 1) we don't control the IP allocation at the GCE network/subnetwork level, so we must ensure that the `manual` network IP address does not conflict with any other GCE subnetwork IP range 2) we need to ensure that on a failure scenario, the route is properly deleted 3) we need to deal with route's conflicts, what happens if a route is already allocated, 4) ...

GCE will allow to configure the VM's private IP address is a near future. So instead of implementing a complex solution, I'd rather prefer to wait until GCE supports this feature.

BTW, there's an aside problem when not enabling `ephemeral_external_ip`: VMs cannot reach the internet, and there's no `HA Internet Gateway` available in GCE, you need to setup one by yourself. This means that when deploying Cloud Foundry, there's a bunch of VMs that needs to have `ephemeral_external_ip` enabled, otherwise, they won't be able to download bits (i.e. at the staging process), they won't be able to talk to some components (the ones that needs to be reached via the system domain, i.e. UAA, ...), ...

I'm going to close this issue and we can track this at https://github.com/frodenas/bosh-google-cpi/issues/1. But feel free to reopen it if you feel it doesn't solve your problem.

Thanks again for reporting this.
